### ISSUE TITLE
executeTableSafeAsync is missing

### ISSUE THREAD

**Issue by nozzlegear** [Zaid-Ajaj/Npgsql.FSharp#1]
Hey! I'm in the middle of writing an app that uses Npgsql to connect to my database and found this project just in time. It looks like you maybe meant to include an `executeTableSafeAsync` function (it's in the README) but it's currently missing from the package on nuget.

**Comment by Zaid-Ajaj** [comment]
Yes, my bad! thanks for pointing that out :pray: it is included in the next package of version 0.3.0 which is being indexed by Nuget now.

**Comment by nozzlegear** [comment]
Great, thanks for the quick update!
