### ISSUE TITLE
Add "Include Error Detail" to the F# API?

### ISSUE THREAD

**Issue by njlr** [Zaid-Ajaj/Npgsql.FSharp#107]
Wondering if there is a way to set "Include Error Detail=true" outside of the connection string?

If not would a PR be accepted?

This setting can be useful for debugging. 

Thanks!

**Comment by Zaid-Ajaj** [comment]
There is a way to do this with the `Sql.config "Include Error Detail=true"` but a PR would be nice to make this more type-safe i.e. `Sql.includeErrorDetail true`

**Comment by Zaid-Ajaj** [comment]
Available as of v5.1.0 🚀
