### ISSUE TITLE
Missing Sql types 

### ISSUE THREAD

**Issue by thomasd3** [Zaid-Ajaj/Npgsql.FSharp#123]
Would it be possible to add the:

Sql.doubleArray
Sql.decimalArray

types?

Right now, there is:

Sql.stringArray
Sql.intArray

but these types are really missing.

**Comment by Zaid-Ajaj** [comment]
Hi there @thomasd3, indeed these functions are missing. Any you could send a PR that adds them to the library? Would really appreciate it 🙏

**Comment by thomasd3** [comment]
@Zaid-Ajaj, done, check pr #124

**Comment by Zaid-Ajaj** [comment]
Closed by #124
