### ISSUE TITLE
Adding cancellation support

### ISSUE THREAD

**Issue by TheAngryByrd** [Zaid-Ajaj/Npgsql.FSharp#13]
I propose adding cancellation tokens to the `task` versions of functions. 

We can either do two things.  Break the existing api to add cancellation tokens or add additional functions with additional suffix (like `readRowTaskCt`) similar to https://github.com/TheAngryByrd/Marten.FSharp/blob/master/src/Marten.FSharp/Marten.FSharp.fs#L767-L816.   

(extracted for brevity)

```fsharp
    let sqlTaskCt<'a> (cancellationToken : CancellationToken) (sqlString : string) (parameters : obj [])  (session : IQuerySession)=
        session.QueryAsync<'a>(sqlString, cancellationToken, parameters=parameters)


    let sqlTask<'a> (sqlString : string) (parameters : obj [])  (session : IQuerySession)=
        sqlTaskCt<'a> CancellationToken.None sqlString parameters session
```

Then that way we can add cancellation tokens easily to the `async` counterparts

```fsharp
    let sqlAsync<'a> (sqlString : string) (parameters : obj []) (session : IQuerySession) = async {
        let! ct = Async.CancellationToken
        return!
            session
            |> sqlTaskCt<'a> ct sqlString parameters
            |> Async.AwaitTask
    }
```

This also turns the `async` functions cold which I believe to be a bonus addition since F# expect `Async`'s to be cold.

**Comment by Zaid-Ajaj** [comment]
Sounds like a good idea, I will look into it soon when time permits. I prefer not to break the current API but if it helps bring the library in the right direction then it is fine! PR's are welcome too, of course :wink:

**Comment by TheAngryByrd** [comment]
I'm fine with doing a PR, I just wanted to discuss it before I work on it :)
