### ISSUE TITLE
Support NpgsqlDataSource

### ISSUE THREAD

**Issue by danieljsummers** [Zaid-Ajaj/Npgsql.FSharp#131]
Npgsql 7 introduced the `NpgsqlDataSource` type ([docs](https://www.npgsql.org/doc/basic-usage.html#data-source), [API](https://www.npgsql.org/doc/api/Npgsql.NpgsqlDataSource.html)) to implement the .NET `DbDataSource` type. It handles integration, connection pooling/threading, etc. It looks like adding support for this to the library would be a minimally-invasive change.

- Add a case to the [`ExecutionTarget` DU](https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/master/src/Npgsql.FSharp.fs#L29)
- Add `Sql.fromDataSource` (or a similarly-named function) to provide the starting point for query construction; it would create `SqlProps` with the new DU case populated from its parameter, similar to how `Sql.existingConnection` currently does
- Modify [`createConnection`](https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/master/src/Npgsql.FSharp.fs#L177) to use the data source's `OpenDbConnection()` method to obtain a connection

If you would like a PR for this, I'd be happy to provide it.

**Comment by Zaid-Ajaj** [comment]
Hi @danieljsummers! it looks you already know the context of the feature 😄 a PR would be great! Happy to review and merge when it lands 🙏

**Comment by Zaid-Ajaj** [comment]
Implemented as of Npgsql.FSharp v5.6.0 🚀
