### ISSUE TITLE
Multiline Insert

### ISSUE THREAD

**Issue by megafinz** [Zaid-Ajaj/Npgsql.FSharp#16]
Is there a way I can express multiline insert operation?
```sql
INSERT INTO table (col1,col2,col3) 
VALUES
  (1, 1, 1),
  (2, 2, 2),
  (3, 3, 3);
```

**Comment by Zaid-Ajaj** [comment]
Hello @megafinz, I am not sure I understand what you mean, can you please elaborate? in any case, whatever query you have, just give it as an argument for the `Sql.query` function as follows:
```fs
let insertQuery = """
INSERT INTO table (col1,col2,col3) 
VALUES
  (1, 1, 1),
  (2, 2, 2),
  (3, 3, 3);
"""

defaultConnection
|> Sql.connect
|> Sql.query insertQuery 
|> Sql.executeNonQuery 
```

**Comment by megafinz** [comment]
@Zaid-Ajaj For a single entity I'd use:
```fsharp
connString
|> Sql.connect
|> Sql.query "INSERT INTO table (col1,col2,col3) VALUES (@col1,@col2,@col3)"
|> Sql.parameters
    [ "col1", entity.Prop1 |> Sql.Value
      "col2", entity.Prop2 |> Sql.Value
      "col3", entity.Prop3 |> Sql.Value ]
|> Sql.executeNonQueryAsync
```

But I'd like to insert a list of entities in a single go. 

>  in any case, whatever query you have, just give it as an argument for the `Sql.query` function

I lose SQL parameters this way, so input is no longer safe.

**Comment by Zaid-Ajaj** [comment]
@megafinz I see, I am afraid that this is not possible as this library doesn't do anything special with regard to [Bulk Copy](https://www.npgsql.org/doc/copy.html) you would need to iterate through your data manually:
```fs
entries
|> List.map (fun entry -> 
  connString
  |> Sql.connect
  |> Sql.query "INSERT INTO table (col1,col2,col3) VALUES (@col1,@col2,@col3)"
  |> Sql.parameters
    [ "col1", entity.Prop1 |> Sql.Value
      "col2", entity.Prop2 |> Sql.Value
      "col3", entity.Prop3 |> Sql.Value ]
  |> Sql.executeNonQueryAsync)
|> Async.Parallel
```

**Comment by megafinz** [comment]
@Zaid-Ajaj Okay, thanks, will use the binary import then.

**Comment by lfr** [comment]
@megafinz why not simply use Zaid's method from [his first response](https://github.com/Zaid-Ajaj/Npgsql.FSharp/issues/16#issuecomment-444989374) and just generate beforehand the last part:
  (1, 1, 1),
  (2, 2, 2),
  (3, 3, 3)
from your list? should be pretty straight forward

**Comment by megafinz** [comment]
@lfr maybe I'm missing something, but I'm pretty sure I'll no longer able to use SQL parameters this way, so I need to manually process values so they are safe to insert to avoid SQL injection risks (which I'd like to avoid).

**Comment by Zaid-Ajaj** [comment]
@lfr Generating the last part by hand may be fine for numbers but for other types of inputs and especially strings, it is not safe! parameterized queries are the way to go

**Comment by rommsen** [comment]
Hey @megafinz. Check out: https://github.com/Zaid-Ajaj/Npgsql.FSharp/issues/30 
It is pretty much exactly what you asked for.

**Comment by megafinz** [comment]
@rommsen Yep, I guess it is, thanks!
