### ISSUE TITLE
Null mapping to option

### ISSUE THREAD

**Issue by gmlion** [Zaid-Ajaj/Npgsql.FSharp#19]
Hello,
I'm getting `System.ArgumentException: Object of type 'Microsoft.FSharp.Core.FSharpOption`1[System.Object]' cannot be converted to type 'Microsoft.FSharp.Core.FSharpOption`1[System.String]'.`

when I try to map a null value to a string option using Sql.parseEachRow

I looked at the code and found two relevant places.

Sql.fs line 628:
`let findRowValue isOptional name row =
            match isOptional, List.tryFind (fun (n, _) -> n = name) row with
            | false, None -> failwithf "Missing parameter: %s" name
            | false, Some (_, x) -> valueAsObject x
            | true, None -> box None
            | true, Some (_, x) -> valueAsOptionalObject x`

here from what I understand we're returning a None in only one case, if the type in the model is optional and the column is missing from the SqlRow object.

Sql.fs line 462:
`let private valueAsOptionalObject = function
    | SqlValue.Short value -> box (Some value)
    | SqlValue.Int value -> box (Some value)
    | SqlValue.Long value -> box (Some value)
    | SqlValue.String value -> box (Some value)
    | SqlValue.Date value -> box (Some value)
    | SqlValue.Bool value -> box (Some value)
    | SqlValue.Number value -> box (Some value)
    | SqlValue.Decimal value -> box (Some value)
    | SqlValue.Bytea value -> box (Some value)
    | SqlValue.HStore value -> box (Some value)
    | SqlValue.Uuid value -> box (Some value)
    | SqlValue.TimeWithTimeZone value -> box (Some value)
    | SqlValue.Null -> box (Some null)`

here None is never returned, and the null sql value is mapped to (Some null).

It looks like the behaviour is different from what stated in the README in the semantic of the option type.
To retain the semantic, I would throw an exception on the missing parameter (no matter whether the type is optional) and map SqlValue.Null to None.

**Comment by gmlion** [comment]
@bratfizyk

**Comment by bratfizyk** [comment]
Hey! Sorry for the late response - I was intentionally away from everything due to Christmas and holiday period :).
Good spot - thanks for the fix.
