### ISSUE TITLE
Question: can I use a regular connection string?

### ISSUE THREAD

**Issue by njlr** [Zaid-Ajaj/Npgsql.FSharp#27]
Can I use a regular connection string with this library?

Docs: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING

Examples:

```
postgresql://
postgresql://localhost
postgresql://localhost:5432
postgresql://localhost/mydb
postgresql://user@localhost
postgresql://user:secret@localhost
postgresql://other@localhost/otherdb?connect_timeout=10&application_name=myapp
postgresql://localhost/mydb?user=other&password=secret
```

I would expect to be able to do something like this: 

```
let! data = 
  "postgresql://user:secret@localhost"
  |> Sql.connect
  |> Sql.query "SELECT * FROM some_table"
  |> Sql.executeTableAsync
```

**Comment by Zaid-Ajaj** [comment]
Your example should work just fine, `Sql.connect` indeed expects a connection string and that is [given](https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/master/src/Sql.fs#L104) to the NpgsqlConnection.

**Comment by njlr** [comment]
I get an error

> Unhandled Exception: System.AggregateException: One or more errors occurred. (Format of the initialization string does not conform to specification starting at index 0.) ---> System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
>    at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
>    at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
>    at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules)
>    at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
>    at Npgsql.NpgsqlConnection.GetPoolAndSettings()
>    at Npgsql.FSharp.SqlModule.newConnection(SqlProps props)
>    at Npgsql.FSharp.SqlModule.executeTableTaskCt@416-1.Invoke(Unit unitVar)
>    at FSharp.Control.Tasks.TaskBuilder.run[a](FSharpFunc`2 firstStep)

However I can connect using the other style `Database=db;Username=abc;Host=...`

**Comment by jchannon** [comment]
Is there a way to pass `Server=localhost;Database=myDb;Uid=foo;Pwd=bar;` and get an object out to connect and query the db?

**Comment by Zaid-Ajaj** [comment]
Hi @jchannon, you can use the literal string as input for the `Sql.connect` function and do stuff from that point on:
```fs
"Server=localhost;Database=myDb;Uid=foo;Pwd=bar;"
|> Sql.connect
|> Sql.query "SELECT * FROM users"
|> Sql.execute (fun read -> read.string "username")
```

**Comment by jchannon** [comment]
I just discovered that 60secs before you reply! Thanks
