### ISSUE TITLE
Insert array values?

### ISSUE THREAD

**Issue by njlr** [Zaid-Ajaj/Npgsql.FSharp#29]
Is it possible to insert array values, such as `character varying[]`? 

`SqlValue` does not appear to cover array cases.

**Comment by Zaid-Ajaj** [comment]
Hello there! This specific type is not yet supported but it should be easy enough to add. I will get to it when I am back from vacation (around the end of next week)

**Comment by njlr** [comment]
Great!

In the mean-time I was able to drop down to the Npgsql level to get it working.

**Comment by Zaid-Ajaj** [comment]
Just ckecked this out and it might turn out a bit more complicated that it looks. 

We can model the type in `SqlValue` as another union case `Array of SqlValue [ ]` but when you read the values as a row from `NpgsqlDataReader` there will be extra work in determining the type of inner values of the arrays. For example, `int[]` will be encoded as `NpgsqlDataType.Array ||| NpgsqlDataType.Int` so we need to get types right.

Another issue is for the `Sql.read*` family of functions, we can't have a generic way of reading all types and we would have to add these functions separately:
```fs
Sql.readIntArray
Sql.readStringArray
// etc.
```
Preferably we would add most common use-cases to this library. 

I am afraid this has low-priority as of now. Feel free to tackle this, PRs are always welcome

**Comment by francesconi** [comment]
I would find this feature useful too.
