### ISSUE TITLE
Async or Task

### ISSUE THREAD

**Issue by rfrerebe** [Zaid-Ajaj/Npgsql.FSharp#3]
Hello,

Would you mind using [TaskBuilder.fs nuget](https://www.nuget.org/packages/TaskBuilder.fs/) instead of your own version ?
Would you also mind having a Task version in addition to Async ?

Thanks

**Comment by Zaid-Ajaj** [comment]
Hi @rfrerebe 

I don't mind doing either things :smile: but it could take a while, I will see what I can do. Unless ofcourse you want to send a PR first ;)

**Comment by rfrerebe** [comment]
Hello,

I will take look and let you know

Thanks

**Comment by rfrerebe** [comment]
Merged
👍 
I let you have look. 
If you are ok, can you publish it on nuget ?
Thanks

**Comment by Zaid-Ajaj** [comment]
Published version 0.6.0 :tada: thanks a lot
