### ISSUE TITLE
type 'Npgsql.NpgsqlDataReader' not found

### ISSUE THREAD

**Issue by halcwb** [Zaid-Ajaj/Npgsql.FSharp#34]
When trying to use your library I get:

> type 'Npgsql.NpgsqlDataReader' not found in assembly 'Npgsql, Version=4.0.8.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'. A possible cause may be a version incompatibility. You may need to explicitly reference the correct version of this assembly to allow all referenced components to use the correct version.

I am trying to use your library in this [script ](https://github.com/halcwb/InformedICU/blob/820b514ccaee6e366587856a3ce2d618e6ea0293/Scripts.fsx)file.

Given the used paket.lock file, however, this should work?:

>     Npgsql (4.0.8) - restriction: || (>= net461) (>= netstandard2.0)
>       System.Memory (>= 4.5.3) - restriction: || (&& (>= net45) (< netstandard2.0)) (&& (< net45) (>= netstandard2.0)) (>= net451)
>       System.Runtime.CompilerServices.Unsafe (>= 4.5.2) - restriction: || (&& (>= net45) (< netstandard2.0)) (&& (< net45) (>= netstandard2.0)) (>= net451)
>       System.Threading.Tasks.Extensions (>= 4.5.2) - restriction: || (&& (>= net45) (< netstandard2.0)) (&& (< net45) (>= netstandard2.0)) (>= net451)
>       System.ValueTuple (>= 4.5) - restriction: || (&& (>= net45) (< netstandard2.0)) (&& (< net45) (>= netstandard2.0)) (>= net451)
>     Npgsql.FSharp (1.11)
>       FSharp.Core (>= 4.3.4) - restriction: || (>= net461) (>= netstandard2.0)
>       Npgsql (>= 3.2.7) - restriction: || (>= net461) (>= netstandard2.0)
>       TaskBuilder.fs (>= 1.1.1) - restriction: || (>= net461) (>= netstandard2.0)
>

**Comment by Zaid-Ajaj** [comment]
Hello there! 

I don't think this actually works because the resolved `Npgsql` version is one major version greater (v4.0.8) than the one `Npgsql.FSharp` library requires (v3.2.7). Try setting the paket resolution strategy to minimum such that you paket.dependencies looks something like 
```
strategy: min

﻿source https://www.nuget.org/api/v2

nuget Expecto
nuget Expecto.BenchmarkDotNet
nuget Expecto.FsCheck
nuget Expecto.Hopac
nuget Npgsql.FSharp ~> 1
nuget Thoth.Json.Net
``` 
Let me know if it worked for you :smile:

**Comment by halcwb** [comment]
Thanks, It seemed to work for another [project](https://github.com/rommsen/EventSourcing-DIY/blob/master/paket.lock). There the Npgsql version is 4.0.6. That's why I thought it would work for me as well.

**Comment by halcwb** [comment]
This worked:

nuget Npgsql ~> 3.2.7
nuget Npgsql.FSharp

Thanks.
