### ISSUE TITLE
Question: multiple related queries within a single transaction

### ISSUE THREAD

**Issue by isnullxbh** [Zaid-Ajaj/Npgsql.FSharp#57]
Hello @Zaid-Ajaj,

is it possible to execute multiple related queries within a single transaction? For example, I have two queries, and one of them requires ID that can be fetched from a result of the execution of another query.
Thanks!

**Comment by Zaid-Ajaj** [comment]
Hello there @isnullxbh, it is possible to execute such query but you need to do it in SQL itself with the `BEGIN TRANSACTION ... COMMIT` syntax, not from this API unfortunately because each query run against the database is atomic unless using `executeTransation` for batch (unrelated) operations

> Sorry about the delay in responding, I thought I already answered a while back 😅

**Comment by isnullxbh** [comment]
Thanks for the explanation, @Zaid-Ajaj !

**Comment by Zaid-Ajaj** [comment]
Anytime :smile: I will close this issue for now, please reopen this or make a new one if you have more questions
