### ISSUE TITLE
Sql.executeSingleRow doesn't exist

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Npgsql.FSharp#66]
The documentation mention a function [Sql.executeSingleRow](https://github.com/Zaid-Ajaj/Npgsql.FSharp#sqlexecutesinglerow-execute-a-query-and-read-a-single-row-back) but it doesn't exist in the source code.

Edit: Perhaps, the title just need to be renamed to `Sql.executeRow` as in the body of the section it is speaking about a `Sql.executeRow` function?

**Comment by Zaid-Ajaj** [comment]
Yeah it is typo, I will fix it in a bit
