### ISSUE TITLE
Sql.executeRow Expected at least one row to be returned from the result set. Instead it was empty

### ISSUE THREAD

**Issue by codingedgar** [Zaid-Ajaj/Npgsql.FSharp#67]
Hi!

I've been using `Sql.executeRow` to return a single row, however when there's no match the fn throws with: `Expected at least one row to be returned from the result set. Instead it was empty`.

Is it possible to add `Sql.tryExecuteRow`? that returns a `row option`?

**Comment by Zaid-Ajaj** [comment]
Hi there @codingedgar, 

The function `Sql.executeRow` is intended for when you know for sure that there will one row or more returned. For example for queries like `SELECT COUNT(*) as user_count FROM users` 

When you can't assume a single row will be returned, you should use `Sql.execute` instead:
```fs
...
|> Sql.execute (fun read -> ...)
|> function 
     | Error error -> printfn "Error occured"
     | Ok [ ] -> (* do something when there are no rows returned *)
     | Ok (firstRow :: rows) -> (* do something with firstRow *)
```
You can write `Sql.tryExecuteRow` yourself using the above (here is one variant)
```fs
module Sql = 
  let tryExecuteRow read props = 
    props
    |> Sql.execute read
    |> function 
          | Error error -> Error error
          | Ok [ ] -> Ok None
          | Ok (firstRow :: rows) -> Ok (Some firstRow)
```

**Comment by codingedgar** [comment]
Thanks! that's exactly what I did 💛

**Comment by ratsclub** [comment]
@Zaid-Ajaj hey, would you be open for a PR introducing the `tryExecuteRow` function on the library?
