### ISSUE TITLE
dotnet 5

### ISSUE THREAD

**Issue by 2mol** [Zaid-Ajaj/Npgsql.FSharp#72]
Hi! I am new to F#, and I realized (after some confusion with `paket`) that this package is probably not compatible with dotnet 5, which came out a week ago.

I am more than happy to create the necessary PR, but I would be happy with a little bit of initial guidance. Is it just a matter of bumping some version numbers/bounds? How do I test build this library?

**Comment by Zaid-Ajaj** [comment]
Hi there @2mol, 

> I realized (after some confusion with paket) that this package is probably not compatible with dotnet 5, which came out a week ago.

Can you please elaborate on the issue? Npgsql.FSharp targets `netstandard2.0` which *is* compatible by dotnet sdk 5 and should work without problems. 

Building/Testing is straightforward. The "hard" part is having a local postgres database with access credentials equal to those used by [the tests](https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/master/tests/Tests.fs#L64-L70) (username=postgres, password=postgres) then 
```bash
cd tests
# Build the project
dotnet build 
# Run the tests
dotnet run
```

**Comment by 2mol** [comment]
Hm, maybe it's about `net5.0` vs. `netcoreapp3.1`.

I basically ran into a similar issue as described here: https://github.com/fsprojects/Paket/issues/3802

So I switched to `<TargetFramework>netcoreapp3.1</TargetFramework>` in fsproj, downgraded to version `3.1.402` and it worked.

I'm working on a minimal reproducible example, I'll post the link to the repo here when I have it.

**Comment by Zaid-Ajaj** [comment]
No problem @2mol, I am glad you were able to resolve the issue :smile:

**Comment by h2physics** [comment]
Anything updated? I also got an issue when I use target framework net5.0 and paket version 5.258.1. 
` The type or namespace name 'HtmlAgilityPack' could not be found (are you missing a using directive or an assembly reference?)`
I used `dotnet build` got the error but when I retry with build action from Visual Studio, the error doesn't happened?
But I need `dotnet build` for CI so please help me to resolve it

**Comment by Zaid-Ajaj** [comment]
Hi there @h2physics the error you are getting
```
The type or namespace name 'HtmlAgilityPack' could not be found (are you missing a using directive or an assembly reference?)
```
is not related to this library. It just means you are missing the package reference. Can you check whether `HtmlAgilityPack` is included in paket.dependencies _and_ paket.references?

**Comment by h2physics** [comment]
Yup, already defined in both paket.dependencies and paket.references. 
My step: 
1. dotnet paket install
2. dotnet restore
3. dotnet build

**Comment by Zaid-Ajaj** [comment]
Then I don't know :/ maybe you can post your question on F# slack with more context: sample project etc?
