### ISSUE TITLE
Is there a way to query based on a list of tuples?

### ISSUE THREAD

**Issue by blakeSaucier** [Zaid-Ajaj/Npgsql.FSharp#74]
Postgres has a really elegant way of doing a pair-wise query like the following:

```
Select * From myTable
Where (id, anotherField) IN
    ((1234, 'a property'), (12345, 'some property'))
```

Can we do this in this library? Or even in Npgsql for that matter?

Thanks!

**Comment by Zaid-Ajaj** [comment]
Hi there @blakeSaucier, to be honest I didn't know this syntax was possible with Postgres hahah 😅 I can't seem to find an example in raw Npgsql docs that uses something like this. Currently this library supports int arrays and string arrays when it comes to using `WHERE ... IN @some_array` but not an array of tuples, I am afraid

**Comment by blakeSaucier** [comment]
Ah I see, thank you for your response.
