### ISSUE TITLE
Sql.Decimal type is always converted to NpgsqlDbType.Money

### ISSUE THREAD

**Issue by blakeSaucier** [Zaid-Ajaj/Npgsql.FSharp#79]
Hi,

Thanks again for the great work on this project, our team is building F# apps and we've enjoyed using this library.

I noticed when inserting into a Postgres `decimal` column, my value is being truncated to two decimal places.

```
let score = 2.48661429815143M
...

|> Sql.query "INSERT INTO ....  (@score)"
|> Sql.parameters [ "score", Sql.decimal ]
```
This results in the value `2.48` being saved into the database.

Looks like it's possible to convert to a double then use `Sql.double`, however I thought I would bring this up as it appears that all uses of `Sql.decimal` results in an `NpgsqlDbType.Money` type being used.

What do you think of adding an `Sql.Money` type in this library which corresponds to the `NpgsqlDbType.Money` type rather than converting all decimals?

Thanks

**Comment by Zaid-Ajaj** [comment]
Hi there @blakeSaucier, 

> our team is building F# apps and we've enjoyed using this library.

Glad to hear that :smile:

> all uses of Sql.decimal results in an NpgsqlDbType.Money type being used.

Yeah this is not entirely correct, I'll fix it sometime soon. In the meantime, you can use `Sql.parameter` to fallback to `NpgsqlParameter` that you can construct yourself. 

> NOTE: update analyzer to follow suit with the changes that will come up here

**Comment by Zaid-Ajaj** [comment]
Published Npgsql.FSharp v3.12.3 which includes the fix 🚀 

Now `Sql.decimal` will map to `NpgsqlDbType.Numeric` (arbitrary-precision decimal) and `Sql.money` will map to `NpgsqlDbType.Money`

Please give it  a try and let me know if all works for you

**Comment by blakeSaucier** [comment]
Thank you, this is great.
