### ISSUE TITLE
The Npgsql.FSharp.Tasks can be tricky, can introduce serious bugs and confusion.

### ISSUE THREAD

**Issue by witoldsz** [Zaid-Ajaj/Npgsql.FSharp#80]
I just wanted to ask if that was possible to introduce methods with `…Throwing` or `…OrThrow` suffix, because – in my opinion – it is very common that there is nothing one can do with failed results other than give up and let the app blow.

This is my case: I have no idea what can I do with infrastructure errors like broken database connections. All I can do is to let the app crash, the system-wide infrastructure will restart it and if that happens, the operational team gets an alert, so they can figure out what is wrong with databases. There is nothing I can do within my app to solve it.

Now I can see there is a new namespace `Npgsql.FSharp.Tasks` which provides almost identical functions with slightly different signatures (result types are not wrapped in result anymore).

Why is it dangerous? Let's say we have two exactly same pieces of code:
- using Npgsql.FSharp: `… |> Sql.executeNonQuery |> ignore`
- using Npgsql.FSharp.Tasks: `… |> Sql.executeNonQuery |> ignore`

So, when you look at that one line of code you cannot tell it you are ignoring ANY kind of errors (like database crashed) or if you are ignoring just the result of successful operation.

The meaning of the line of code changes dramatically based on `open` declaration in a different place of a file. In my opinion, it can lead to critical bugs in application, because it's so easy to misuse the API.

**Comment by witoldsz** [comment]
Just a side note, I would see no harm in adding extra variations of same functions in API like:
`Sql.executeNonQuery`
`Sql.executeNonQueryAsync`
`Sql.executeNonQueryOrThrow`
`Sql.executeNonQueryWhetElseIsUseful`

or maybe:

`Sql.execute.result.NonQuery`
`Sql.execute.asyncResult.NonQuery`
`Sql.execute.throwing.NonQuery`
`Sql.execute.whetElse.NonQuery`

however, in each case it is so clear what are we dealing with. Each line of code describes itself.

**Comment by witoldsz** [comment]
One more thing I have just noticed: what is the difference between
- `Npgsql.FSharp.Sql.connect` and
- `Npgsql.FSharp.Tasks.connect`?

There are much more functions like `host/port/username…` (and they use some private functions and structures as well) basically all the configuration stuff, then there is the new `Sql.transaction` – all of them are now written twice? Was that copy'n paste and new features must be, from now on, duplicated for each "branch"?

**Comment by Zaid-Ajaj** [comment]
Hi @witoldsz, so there seem to multiple things that are not to your liking here. First of all, the fact that you can open two namespaces `Npgsql.FSharp` and `Npgsql.FSharp.Tasks` in the same file. Yes, this was a concern for me too when I started implementing the recent features. I had two options: implement a new namespace or publish a new library and I went with the former and changed the docs accordingly: when you start using the library, you choose a namespace (one of the two) and _stick_ with it throughout the application. I believe this shouldn't be a hard thing to follow because if you are using tasks or asyncs in your app, you will know right away if you used the "wrong" namespace.

 > I just wanted to ask if that was possible to introduce methods with …Throwing or …OrThrow suffix, because – in my opinion – it is very common that there is nothing one can do with failed results other than give up and let the app blow.

> This is my case: I have no idea what can I do with infrastructure errors like broken database connections. All I can do is to let the app crash, the system-wide infrastructure will restart it and if that happens, the operational team gets an alert, so they can figure out what is wrong with databases. There is nothing I can do within my app to solve it.

The `Npgsql.FSharp.Tasks` namespace was introduced to solve this problem: the functions there like `Sql.execute`, `Sql.executeRow` etc. do _not_ catch any exceptions and instead let them bubble up into the application and there will usually be some global handler that catches them eventually to log them or whatnot. 

> all of them are now written twice? Was that copy'n paste and new features must be, from now on, duplicated for each "branch"?

They are written twice with slightly different implementation details. I don't plan on adding more "branches" and I believe the next v4.x of the library will only be exposing the functionality under `Npgsql.FSharp.Tasks` as the default (if that is even necessary in the first place)

**Comment by witoldsz** [comment]
> so there seem to multiple things that are not to your liking here…

It doesn't really matter *what I like or not*, does it? What matters is that new changes can introduce serious bugs, like I said before.

> First of all, the fact that you can open two namespaces Npgsql.FSharp and Npgsql.FSharp.Tasks in the same file. 

That idea did not crossed my mind.

> I had two options: implement a new namespace or publish a new library

I don't get it. You could just add **few new functions and that would be it**. Someone throw the idea of copy/paste all the lib into new namespace, tweak few functions so they return something else. It might sound cool, but at the end, what I see is the worst of two worlds:
- it forced you to copy'n paste and keep it that way, few functions slightly changed, rest are just copied and stay that way, so now you have to maintain them twice,
- now the API can be confusing, because the pieces of code change their meaning _silently_, i.e. hidden from type checker and from the eyes of the reader of the code

>  when you start using the library, you choose a namespace

Again: it is now easy to introduce a bug when using this lib. You can *choose* a namespace and type it at the top of the file, or you can write a function, hit `ctrl+space, enter` twice and not even notice you have imported the "wrong" namespace. Or you can copy/paste few lines of code from elsewhere and the exact same piece of code, while being 100% OK there, is now a bug here.

Please, do not take it personal. I like this library, I would not spend my time writing all this if I don't care. Take my words or ignore it, no offense.

**Comment by Zaid-Ajaj** [comment]
> Please, do not take it personal. I like this library, I would not spend my time writing all this if I don't care. Take my words or ignore it, no offense.

I really appreciate your feedback 🙏 

> You could just add few new functions and that would be it

That's the thing, I didn't want to add more functions to keep the public API surface as small as possible but my alternative approach might do more harm than good here.

I think I will make the async-returning functions obsolete in favor of their "equivalent" from `Npgsql.FSharp.Tasks`. This way, these changes won't be _silent_ anymore and users will be directed towards the `Task` based functions. What do you think of this proposal?

**Comment by ericsampson** [comment]
Or split into two packages…

**Comment by Zaid-Ajaj** [comment]
As of v4.0 there are no longer two namespaces, just `Npgsql.FSharp`  which what `Npgsql.FSharp.Tasks` previously provided but now it is the default
