### ISSUE TITLE
Custom parameters have different semantics than other parameters

### ISSUE THREAD

**Issue by retendo** [Zaid-Ajaj/Npgsql.FSharp#82]
Hi,

first of all thanks for this great library, I look forward to using it in production in a few weeks!

I do have a concern regarding the reference semantics with custom parameters, though.
If you opt to use them you have to create a custom NpgsqlParameter and manage their lifecycle, in particular NOT reuse them, as you would get an error like: 

> The parameter already belongs to a collection

In situations where you would like to query more than once with the same WHERE clause (i.e. get paginated list and then get total count) this is a pain to manage when you want to stay flexible with building the queries.

In contrast if you would use one of the other parameter union types like for example intArray you would get a freshly created NpgsqlParameter every single query:

https://github.com/Zaid-Ajaj/Npgsql.FSharp/blob/10437013f4b8688932f5238e991a8f44cbf6b738/src/Npgsql.FSharp.Tasks.fs#L215

I think there should be more straightforward way to use custom parameters and still have this comfort.

My proposal would be to have a new case in the Common.SqlValue union:
```FSharp
type SqlValue =
    | ParameterValueType of obj * NpgsqlDbType
    ...
```
and then in populateRow
```FSharp
match value with
| SqlValue.ParameterValueType (value, valueType) -> add value valueType
...
```

Alternatively, for my case it would also be enough to just have something for int64Arrays. ;)

**Comment by retendo** [comment]
Submitted a pull request for the int64Array version for now, as this is all I need at the moment.

**Comment by witoldsz** [comment]
There is a `Sql.parameter` accepting a raw `NpgsqlParameter` object (returning `SqlValue`).
I use it when I need some extra constructs not available by default, like this:

```
module SqlX =

    let opt (f: 'a -> SqlValue) : 'a option -> SqlValue =
        Option.map f >> Option.defaultValue Sql.dbnull

    let varchar (value: string) : SqlValue =
        NpgsqlParameter(NpgsqlDbType = NpgsqlDbType.Varchar, NpgsqlValue = value)
        |> Sql.parameter

    let char (value: string) : SqlValue =
        NpgsqlParameter(NpgsqlDbType = NpgsqlDbType.Char, NpgsqlValue = value)
        |> Sql.parameter

    /// warning: make sure dbType corresponds to 'a generic type
    let private arr (dbType: NpgsqlDbType) (arrValues: 'a array) : SqlValue =
        NpgsqlParameter(NpgsqlDbType = (NpgsqlDbType.Array ||| dbType), NpgsqlValue = arrValues)
        |> Sql.parameter

    let boolArr: bool array -> SqlValue = arr NpgsqlDbType.Boolean

    let dateArr (values: LocalDate array) : SqlValue =
        arr NpgsqlDbType.Date [| for v in values -> v.ToDateOnly() |]

    let instantArr: Instant array -> SqlValue =
        Array.map NodaX.instantToDateTimeUnspecified >> arr NpgsqlDbType.Timestamp

    let instant: Instant -> SqlValue =
        NodaX.instantToDateTimeUnspecified >> Sql.timestamp

    let date (value: LocalDate) : SqlValue = Sql.date (value.ToDateOnly())
```

Would that work for you?

**Comment by Zaid-Ajaj** [comment]
@witoldsz Indeed, that is the solution for the issue.
