### ISSUE TITLE
Sql.transaction is unnecessary

### ISSUE THREAD

**Issue by trungdo-epi** [Zaid-Ajaj/Npgsql.FSharp#87]
If we create a transaction using `connection.BeginTransaction()`, then the connection is attached to the transaction. Therefore, we can just use `Sql.existingConnection` in every sql statements afterward. Moreover, we can remove `Transaction` from `ExecutionTarget`.

**Comment by Zaid-Ajaj** [comment]
You are right, it is kind of redundant at this point. I will remove it in some future version, right now it is harmless if used.

**Comment by trungdo-epi** [comment]
I think `Sql.executeTransaction` should not begin a transaction. Instead, users should explicitly control transactions. Like:

```
use con = ...
use tx = con.BeginTransaction()

Sql.existingConnection con
|> Sql.executeTransaction ...

con.Commit()
```

This approach has a benefit that we can span the transaction to whatever commands we like. For example:

```
use con = ...
use tx = con.BeginTransaction()

Sql.existingConnection con
|> Sql.executeTransaction ...

Sql.existingConnection con
|> Sql.executeNonQuery ...

con.Commit()
```

If it is the case, we should rename `executeTransaction` to `executeBatch` or `executeMultiple`, etc.

**Comment by Zaid-Ajaj** [comment]
That is very interesting @trungdo-epi I think it makes more sense this way. Can we already check that a transaction has started for the connection and not start one internally from `Sql.executeTransaction` if that is case?

**Comment by trungdo-epi** [comment]
I don't know how to check if a connection has started a transaction.

But I can think of a possible solution that we use `Sql.existingConnection` exclusively. _Dapper does that_. Users have the responsibility to create connection and transaction explicitly.

In the lib, we don't need to care about transaction as npgsql ignores this.
https://www.npgsql.org/doc/api/Npgsql.NpgsqlCommand.html#Npgsql_NpgsqlCommand_Transaction

The doc says

> This property is ignored by Npgsql. PostgreSQL only supports a single transaction at a given time on a given connection, and all commands implicitly run inside the current transaction started via `connection.BeginTransaction`

_I added `connection.BeginTransaction` in the quote._

I think this approach adds a bit of consistency. We no longer have multiple ways to connect to the database via `Sql.connect`, `Sql.existingConnection` and `Sql.transaction`.

But it is just my thinking. I would love to hear your opinions.

**Comment by Zaid-Ajaj** [comment]
I agree that `Sql.transaction` is redundant. I think we can deprecate it (not entirely remove it) in the next major version but I will probably need to add a proper documentation website to showcase the different scenarios and how to properly work with transactions.

**Comment by Zaid-Ajaj** [comment]
Removed as of v4.0
