### ISSUE TITLE
Consider reducing whitespaces of Sql.query

### ISSUE THREAD

**Issue by trungdo-epi** [Zaid-Ajaj/Npgsql.FSharp#90]
I usually write multiple lines queries like

```fs
Sql.connect str
|> Sql.query """
   update xx
   set a = x,
       b = y
"""
```
I think it would be fine to reduce whitespaces of the query. Maybe we can use `Regex.Replace(sql, @"\s+", " ")`.

**Comment by Zaid-Ajaj** [comment]
Hi there @trungdo-epi, why do you want to trim the whitespace? It could result in a bad query. This is something that you can do from your application and not so much from the library like this
```fs
let cleanQuery (input: string) = Regex.Replace(input, @"\s+", " ")

let sql = cleanQuery """
   update xx
   set a = x,
       b = y
"""

connectionString
|> Sql.connect
|> Sql.query sql 
```

**Comment by trungdo-epi** [comment]
I want to trim whitespaces because I think it would reduce the amount of data transferred to the database. I guess I should do that in application code. Thanks.

**Comment by Zaid-Ajaj** [comment]
> I think it would reduce the amount of data transferred to the database

Unless you are sending huge queries with megabytes of text, this wouldn't improve anything significantly. Of course, that is up to you decide 😉
