### ISSUE TITLE
question: how can I insert lists?

### ISSUE THREAD

**Issue by thomasd3** [Zaid-Ajaj/Npgsql.FSharp#96]
let's say I have:

    type A =
        {
            a: string
            b: int
        }

and then and list of it: let l : A list = [.....]

how can I batch insert that list and map the fields to the columns?

**Comment by Zaid-Ajaj** [comment]
Hi there, check out https://zaid-ajaj.github.io/Npgsql.FSharp/#/usecases/batch-updates-or-inserts from the docs which explain transactions to insert multiple rows in one go

**Comment by thomasd3** [comment]
I had missed that whole section with use cases! thanks a lot!
