### ISSUE TITLE
Extremely slow batch insert

### ISSUE THREAD

**Issue by thomasd3** [Zaid-Ajaj/Npgsql.FSharp#97]
I am using this schema:

```
        let tableCreationSQL =
            $"CREATE TABLE IF NOT EXISTS {tableName} (
                instrument varchar NOT NULL,
                ts timestamp without time zone NOT NULL,
                price decimal NOT NULL,
                volume decimal NOT NULL
            );

            CREATE INDEX IF NOT EXISTS idx_instrument ON {tableName}(instrument);
            CREATE INDEX IF NOT EXISTS idx_ts ON {tableName}(ts);"

```

and this insertion code:

```
    let insertTradesAsync (trades: TradeData list) : Async<Result<int, Exception>> =
        async {
            try
                let data =
                    trades
                    |> List.map (fun t ->
                            [
                                "@instrument", Sql.text      t.Instrument.Ticker
                                "@ts",         Sql.timestamp t.Timestamp.DateTime
                                "@price",      Sql.decimal   t.Price
                                "@volume",     Sql.decimal   (t.Quantity * t.Price)
                            ]
                        )

                let! result =
                    connectionString
                    |> Sql.connect
                    |> Sql.executeTransactionAsync [ "INSERT INTO buffer_trades (instrument, ts, price, volume) VALUES (@instrument, @ts, @price, @volume)", data]
                    |> Async.AwaitTask
                return Ok (List.sum result)

            with ex ->
                return Error ex
        }

```

When inserting batches of 500 to 3000 records, it will take between 20 and 80 seconds.
When I do batches of 100, It takes 3-5 seconds to do the insertion.

Is there anything wrong in the way I'm using the lib?

**Comment by Zaid-Ajaj** [comment]
Hi there @thomasd3 thanks for filing the issue. I don't think you are using the library incorrectly and I will have to check out why it is slow.

I will let you know how it goes

**Comment by thomasd3** [comment]
I have this SO thread as well: https://stackoverflow.com/questions/68597323/batch-insert-in-postgresql-extremely-slow-f

Showing some tests I have done: Whether it's a laptop or a very large AWS instance, the results are equally bad.

The operation is not IO, memory or disk bound, the system is mostly idle, so there is something else holding it.

The initial writes are very fast, then withing 5-6 batches it slows down, so I thought it could be an issue with writing to disk, but it doesn't seem like it from what I can see.
During the long insert times, there is almost nothing happening.

**Comment by thomasd3** [comment]
I just found that executeTransaction performs significantly better than executeTransactionAsync.

**Comment by JesseALancaster** [comment]
Any update on this? I'm also looking for support for bulk inserts/updates. `executeTransactionAsync`  I also find very slow, even for just a few hundred records.

`executeTransaction `and `executeTransactionAsync ` just serially execute queries in a transaction though right? It's not actually a bulk operation?

If so, is there support for bulk operations? If not, any idea why it's so slow?

**Comment by JesseALancaster** [comment]
I confirmed by turning on logging, that this is not batch support, 
```
    "INSERT INTO ... VALUES (@number)", [
            [ "@number", Sql.int 1 ]
            [ "@number", Sql.int 2 ]
            [ "@number", Sql.int 3 ]
        ]
```
Creates 3 statements as the docs indicate, who while saving on a commit until the end is great, it's not surprising it's slow if the goal is batch insertion.

@Zaid-Ajaj is there a way to create a SINGLE insert statement with multiple sets of values, so the result is
```
INSERT INTO ... VALUES
("@number", Sql.int 1),
("@number", Sql.int 2),
("@number", Sql.int 3)
```
?

**Comment by thomasd3** [comment]
@Zaid-Ajaj is there any plan to address this?

**Comment by Ildhesten** [comment]
In the current implementation, a round-trip is made to the database per insert. This of course rather slow, and traditionally, the advice has been to batch up multiple commands into a single SQL statement for better performance.

However, with Npgsql 6.0, they have introduced a new [batching API](https://www.npgsql.org/doc/release-notes/6.0.html). This is pretty straightforward to use and should result in substantial speed-up for larger workloads. Unfortunately upgrading to Npgsql 6.0 also comes with some breaking changes about the handling of timezones. Something that this package has a unit test for "DateTimeOffset roundtrip when input is local", so it may be important to some people.

If we decide to upgrade, introducing batched updates per query, seems pretty straightforward by modifying the bottom part of e.g. `executeTransactionAsync` to:
````fsharp
use batch = new NpgsqlBatch(connection, transaction)
for parameterSet in parameterSets do
  let batchCommand = new NpgsqlBatchCommand(query)
  populateBatchRow batchCommand parameterSet
  batch.BatchCommands.Add(batchCommand)
  let! affectedRows = batch.ExecuteNonQueryAsync props.CancellationToken
  affectedRowsByQuery.Add affectedRows
````
Where `populateBatchRow` matches its `populateRow` counterpart, for regular commands.

However there may be some oddities regarding batch commands, how they return the numbers of rows affected, etc. so while the change looks straightforward, it may come with caveats down the line.

I have a branch where batch updates seem to run rather pain-free on my machine, and I can turn it into a PR if need be.

When it comes to releasing it into the wild, I would recommend a major version bump and some time in preview as a NuGet package though.

@Zaid-Ajaj What do you think?

**Comment by Zaid-Ajaj** [comment]
Hi @Ildhesten, the new batch API looks great! if it easily fixes this problem and the public API looks the same, then it is a no-brainer that we should uprade to Npgsql.FSharp. 

> When it comes to releasing it into the wild, I would recommend a major version bump and some time in preview as a NuGet package though.

A major version bump sounds good, a preview release isn't needed IMO. 

> I can turn it into a PR if need be.

Yes, please 🙏 !

**Comment by thomasd3** [comment]
I'd be happy to test the preview package.

**Comment by Ildhesten** [comment]
Sorry for the delay, but I have just sent in a pull request #118 where executeTransactionAsync now utilizes batching. It may also possibly address issue #117

**Comment by Zaid-Ajaj** [comment]
@thomasd3 @Ildhesten Npgsql.FSharp v5.0.1 has been published, it now uses the batch API thanks to @Ildhesten please give it a go and let me how it goes 🙏
